### ISSUE TITLE
ESM target is missing

### ISSUE THREAD

**Issue by PaulLeCam** [ChainAgnostic/caip-js#22]
The [`module` field is defined in package.json](https://github.com/ChainAgnostic/caip-js/blob/bd1f3555325783aa334f69070e685b71b2054a01/package.json#L22) but the [`build` script](https://github.com/ChainAgnostic/caip-js/blob/bd1f3555325783aa334f69070e685b71b2054a01/package.json#L39) doesn't seem to create the file(s).

This results in the package currently published on npm not being usable with ESM bundlers such as [Vite](https://vitejs.dev/).

**Comment by samuveth** [comment]
I'm also waiting for this to be fixed

**Comment by shavinac** [comment]
i think this is fixed with the new release 1.1.0 https://github.com/ChainAgnostic/caip-js/releases/tag/1.1.0 ?

**Comment by PaulLeCam** [comment]
Closing as it's fixed in v1.1.0
